### ISSUE TITLE
Pandora Setting and Pianobar error

### ISSUE THREAD

**Issue by Nate-mycroft** [ethanaward/pianobar-skill#21]
When you say Hey Mycroft play Pandora, it responds back with an error about my username and password are wrong, then is followed by an error in pianobar. This same issue happened with another one of my units and @Mn0491 found the issue that pianobar was looking for a folder, but it was turned into a directory.

Will send logs

**Comment by ErkFrr** [comment]
having same issue.. anyone have any luck?

**Comment by ErkFrr** [comment]
here is my error, i am doing my best to find a solution... im not the brightest, but who knows..


07:48:19.981 - mycroft.client.speech.main:handle_utterance:61 - INFO - Utterance: [u'play pandora']
07:48:19.990 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
~~~~session": "e10e83a4-e3f6-4aee-85f9-e62c8d16df01", "utterances": ["play pandora"]}, "context": {"client_name": "mycroft_listener", "ident": "1517644096.71274288879"}}
07:48:20.010 - mycroft.skills.intent_service:send_metrics:246 - DEBUG - Sending metric
07:48:20.016 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
~~~~ "pandora"}], "PlayKeyword": "play", "utterance": "play pandora"}, "context": {"client_name": "mycroft_listener", "ident": "1517644096.71274288879", "target": null}}
07:48:20.070 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.start", "data": {"handler": "PianobarSkill.play_pandora"}, "context": null}
07:48:20.070 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.start", "data": {"handler": "PianobarSkill.play_pandora"}, "context": null}
ERROR: Failed to load plugin /usr/lib/ao/plugins-4/libesd.so => dlopen() failed
ERROR: Failed to load plugin /usr/lib/ao/plugins-4/libnas.so => dlopen() failed
~~~~- requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "POST /v1/device/6523174c-6b79-44d1-bedd-32371ca42df4/metric/timing HTTP/1.1" 200 289
~~~~- requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "POST /v1/device/6523174c-6b79-44d1-bedd-32371ca42df4/metric/timing HTTP/1.1" 200 280
07:48:22.164 - pianobar-skill__init__:_get_station:293 - INFO - 'stations'
~~~~andora failed to load, your email and password maybe incorrect."}, "context": {"client_name": "mycroft_listener", "ident": "1517644096.71274288879", "target": null}}
07:48:22.182 - pianobar-skill__init__:play_pandora:317 - INFO - None
~~~~data": {"expect_response": false, "utterance": "playing pandora"}, "context": {"client_name": "mycroft_listener", "ident": "1517644096.71274288879", "target": null}}
07:48:22.222 - mycroft.util:wait_while_speaking:253 - INFO - mycroft.utils.wait_while_speaking() is depreciated, use mycroft.audio.wait_while_speaking() instead.
07:48:22.248 - SKILLS - DEBUG - {"type": "recognizer_loop:audio_output_start", "data": {}, "context": null}
Traceback (most recent call last):
File "/opt/mycroft/skills/pianobar-skill/event_command.py", line 55, in <module>
with open(now_playing, 'w') as f:
IOError: [Errno 21] Is a directory: '/home/mycroft/.config/pianobar/info'
07:48:27.034 - SKILLS - DEBUG - {"type": "enclosure.eyes.blink", "data": {"side": "b"}, "context": null}
07:48:28.655 - SKILLS - DEBUG - {"type": "recognizer_loop:audio_output_end", "data": {}, "context": null}
07:48:28.684 - mycroft.skills.core:wrapper:663 - ERROR - An error occurred while processing a request in PianobarSkill
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/mycroft_core-0.9.16-py2.7.egg/mycroft/skills/core.py", line 639, in wrapper
handler(message)
File "/opt/mycroft/skills/pianobar-skill/__init__.py", line 332, in play_pandora
self.settings["stations"][0][0], speak=False)
File "/usr/local/lib/python2.7/site-packages/mycroft_core-0.9.16-py2.7.egg/mycroft/skills/settings.py", line 169, in __getitem__
return super(SkillSettings, self).__getitem__(key)
KeyError: 'stations'

**Comment by LearnedVector** [comment]
this should be fixed with the newest commit
