### ISSUE TITLE
Cannot log in to pandora - password is correct

### ISSUE THREAD

**Issue by owiuefiweytgt** [ethanaward/pianobar-skill#53]
Cannot log in to pandora, copy pasted the pasword into the pandora website so I know it's good and it works.

I get a "Pandora failed to load, please check your password...." message if I try to use the skill.

**Comment by juca-cruz** [comment]
Same here, I am using the correct credentials.

> pianobar-skill:_launch_pianobar_process:315 - ERROR - Failed to connect to Pandora
Traceback (most recent call last):
  File "/opt/mycroft/skills/pianobar-skill/__init__.py", line 312, in _launch_pianobar_process
    self._load_current_info()
  File "/opt/mycroft/skills/pianobar-skill/__init__.py", line 274, in _load_current_info
    info = json.load(f)
  File "/usr/lib/python3.4/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

Also I am not having any issues with the CLI vanilla version of [Pianobar](https://6xq.net/pianobar/) in my Mac but I can't make it work in Mycroft.
